nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.4.1.cjs

npmScopes:
  chewy:
    npmAlwaysAuth: true
    npmAuthToken: "${YARN_NPM_AUTH_TOKEN}"
    npmRegistryServer: 'https://chewyinc.jfrog.io/chewyinc/api/npm/npm/'
